version: "3.6"

services:
  docker-auto-backup:
    build: docker-auto-backup/
    container_name: docker-auto-backup

    restart: unless-stopped
    init: true

    environment:
      CRON_EXPR: "0 4 * * *"
      ENABLE_RSYNC: "y"
      ROTATE_AFTER: 5
      RSYNC_DEST: $RSYNC_DEST
      SSH_HOST: $SSH_HOST

    volumes:
      - vol_docker-auto-backup:/backup:ro
      - ./archive/:/archive
      - ./pubkey.gpg:/root/encryption_key:ro
      - ./id_rsa:/root/.ssh/ssh_key:ro
      - ./known_hosts:/root/.ssh/known_hosts:ro

volumes:
  vol_docker-auto-backup:
    name: vol_docker-auto-backup
