name: Deployment
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker agent meta
        id: docker_agent_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: eerotal/restic-docker-swarm-agent
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Docker server meta
        id: docker_server_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: eerotal/restic-docker-swarm-server
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build agent image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./agent/
          file: ./agent/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/386, linux/arm/v6, linux/arm/v7
          push: true
          tags: ${{ steps.docker_agent_meta.outputs.tags }}

      - name: Build server image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          file: ./server/Dockerfile
          platforms: linux/amd64, linux/arm64, linux/386, linux/arm/v6, linux/arm/v7
          push: true
          tags: ${{ steps.docker_server_meta.outputs.tags }}
